services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\ProductCatalogDateAttribute\EventSubscriber\:
        resource: './../../EventSubscriber'
        tags:
            - name: kernel.event.subscriber

